-- FrenchiePal V2
-- Schema tracking + dashboard KPI per Supabase/Postgres
-- Eseguire questo script nel SQL Editor di Supabase

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.landing_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  landing_version text not null default 'v2',
  device_type text not null check (device_type in ('mobile', 'desktop')),
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz null,
  lead_captured boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.landing_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_name text not null,
  source_section text null,
  device_type text not null check (device_type in ('mobile', 'desktop')),
  landing_version text not null default 'v2',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.landing_leads (
  id bigint generated by default as identity primary key,
  session_id text null,
  email text not null,
  lead_source text not null check (lead_source in ('form', 'chat')),
  landing_version text not null default 'v2',
  feature_priority text null,
  experience_rating integer null check (experience_rating between 1 and 5),
  assistant_topic text null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_sessions (
  id bigint generated by default as identity primary key,
  chat_session_id text not null unique,
  session_id text not null,
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz null,
  device_type text not null check (device_type in ('mobile', 'desktop')),
  entry_point text not null default 'assistant',
  email_captured boolean not null default false,
  feature_priority text null,
  experience_rating integer null check (experience_rating between 1 and 5),
  inferred_topic text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  chat_session_id text not null,
  role text not null check (role in ('user', 'assistant')),
  message_text text not null,
  message_order integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (chat_session_id, message_order)
);

alter table public.landing_events
  alter column session_id set not null;

alter table public.landing_leads
  add column if not exists landing_version text;

update public.landing_leads
set landing_version = 'v2'
where landing_version is null;

alter table public.landing_leads
  alter column landing_version set default 'v2';

alter table public.landing_leads
  alter column landing_version set not null;

create index if not exists idx_landing_sessions_started_at
  on public.landing_sessions (started_at desc);

create index if not exists idx_landing_sessions_device_type
  on public.landing_sessions (device_type);

create index if not exists idx_landing_events_name_created
  on public.landing_events (event_name, created_at desc);

create index if not exists idx_landing_events_session
  on public.landing_events (session_id);

create index if not exists idx_landing_events_version_created
  on public.landing_events (landing_version, created_at desc);

create index if not exists idx_landing_events_metadata_gin
  on public.landing_events using gin (metadata);

create index if not exists idx_landing_leads_source_created
  on public.landing_leads (lead_source, created_at desc);

create index if not exists idx_landing_leads_session
  on public.landing_leads (session_id);

create index if not exists idx_landing_leads_version_created
  on public.landing_leads (landing_version, created_at desc);

drop index if exists public.idx_landing_leads_email_source;

create index if not exists idx_landing_leads_email
  on public.landing_leads (lower(email));

create index if not exists idx_chat_sessions_session_id
  on public.chat_sessions (session_id);

create index if not exists idx_chat_sessions_started_at
  on public.chat_sessions (started_at desc);

create index if not exists idx_chat_messages_chat_session_order
  on public.chat_messages (chat_session_id, message_order);

create index if not exists idx_chat_messages_created_at
  on public.chat_messages (created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fk_landing_events_session'
  ) then
    alter table public.landing_events
      add constraint fk_landing_events_session
      foreign key (session_id)
      references public.landing_sessions(session_id)
      on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fk_landing_leads_session'
  ) then
    alter table public.landing_leads
      add constraint fk_landing_leads_session
      foreign key (session_id)
      references public.landing_sessions(session_id)
      on delete set null;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fk_chat_sessions_session'
  ) then
    alter table public.chat_sessions
      add constraint fk_chat_sessions_session
      foreign key (session_id)
      references public.landing_sessions(session_id)
      on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fk_chat_messages_session'
  ) then
    alter table public.chat_messages
      add constraint fk_chat_messages_session
      foreign key (chat_session_id)
      references public.chat_sessions(chat_session_id)
      on delete cascade;
  end if;
end
$$;

drop trigger if exists trg_landing_sessions_updated_at on public.landing_sessions;
create trigger trg_landing_sessions_updated_at
before update on public.landing_sessions
for each row execute function public.set_updated_at();

drop trigger if exists trg_chat_sessions_updated_at on public.chat_sessions;
create trigger trg_chat_sessions_updated_at
before update on public.chat_sessions
for each row execute function public.set_updated_at();

create or replace view public.dashboard_kpi_overview_v2 as
with
sessions as (
  select count(*)::bigint as total_sessions
  from public.landing_sessions
  where landing_version = 'v2'
),
events as (
  select
    count(distinct case when event_name = 'demo_open' then session_id end)::bigint as demo_open_sessions,
    count(distinct case when event_name = 'demo_open_mobile_fullscreen' then session_id end)::bigint as demo_open_mobile_fullscreen_sessions,
    count(distinct case when event_name = 'click_assistant' then session_id end)::bigint as assistant_sessions,
    count(distinct case when event_name = 'click_alert' then session_id end)::bigint as alert_sessions,
    count(distinct case when event_name = 'assistant_user_message_sent' then session_id end)::bigint as assistant_message_sessions,
    count(distinct case when event_name = 'assistant_suggested_question_click' then session_id end)::bigint as suggested_question_sessions,
    count(distinct case when event_name = 'form_submit' then session_id end)::bigint as form_submit_sessions,
    count(distinct case when event_name = 'chat_email_submitted' then session_id end)::bigint as chat_email_sessions,
    count(distinct case when event_name = 'lead_captured' then session_id end)::bigint as lead_sessions
  from public.landing_events
  where landing_version = 'v2'
),
leads as (
  select
    count(*)::bigint as total_leads,
    count(*) filter (where lead_source = 'form')::bigint as form_leads,
    count(*) filter (where lead_source = 'chat')::bigint as chat_leads
  from public.landing_leads
  where landing_version = 'v2'
),
chat as (
  select
    count(*)::bigint as total_chat_sessions,
    avg(cs.experience_rating)::numeric(10,2) as avg_experience_rating,
    count(*) filter (where cs.email_captured = true)::bigint as chat_sessions_with_email
  from public.chat_sessions cs
  inner join public.landing_sessions ls
    on ls.session_id = cs.session_id
  where ls.landing_version = 'v2'
)
select
  s.total_sessions,
  l.total_leads,
  l.form_leads,
  l.chat_leads,
  e.demo_open_sessions,
  e.demo_open_mobile_fullscreen_sessions,
  e.assistant_sessions,
  e.alert_sessions,
  e.assistant_message_sessions,
  e.suggested_question_sessions,
  e.form_submit_sessions,
  e.chat_email_sessions,
  e.lead_sessions,
  c.total_chat_sessions,
  c.chat_sessions_with_email,
  c.avg_experience_rating,
  round(100.0 * l.total_leads / nullif(s.total_sessions, 0), 2) as lead_conversion_rate_pct,
  round(100.0 * e.demo_open_sessions / nullif(s.total_sessions, 0), 2) as demo_open_rate_pct,
  round(100.0 * e.demo_open_mobile_fullscreen_sessions / nullif(s.total_sessions, 0), 2) as mobile_fullscreen_rate_pct,
  round(100.0 * e.assistant_sessions / nullif(s.total_sessions, 0), 2) as assistant_entry_rate_pct,
  round(100.0 * e.alert_sessions / nullif(s.total_sessions, 0), 2) as alert_click_rate_pct,
  round(100.0 * e.suggested_question_sessions / nullif(e.assistant_sessions, 0), 2) as suggested_question_ctr_pct
from sessions s
cross join events e
cross join leads l
cross join chat c;

create or replace view public.dashboard_assistant_funnel_v2 as
with steps as (
  select 1 as step_order, 'page_view'::text as step_name, count(distinct session_id)::bigint as sessions
  from public.landing_events
  where event_name = 'page_view'
    and landing_version = 'v2'

  union all

  select 2, 'demo_open', count(distinct session_id)::bigint
  from public.landing_events
  where event_name = 'demo_open'
    and landing_version = 'v2'

  union all

  select 3, 'click_assistant', count(distinct session_id)::bigint
  from public.landing_events
  where event_name = 'click_assistant'
    and landing_version = 'v2'

  union all

  select 4, 'assistant_user_message_sent', count(distinct session_id)::bigint
  from public.landing_events
  where event_name = 'assistant_user_message_sent'
    and landing_version = 'v2'

  union all

  select 5, 'chat_email_submitted', count(distinct session_id)::bigint
  from public.landing_events
  where event_name = 'chat_email_submitted'
    and landing_version = 'v2'

  union all

  select 6, 'lead_captured_chat', count(distinct session_id)::bigint
  from public.landing_events
  where event_name = 'lead_captured'
    and landing_version = 'v2'
    and coalesce(metadata ->> 'lead_source', '') = 'chat'
)
select
  step_order,
  step_name,
  sessions,
  lag(sessions) over (order by step_order) as previous_step_sessions,
  round(
    100.0 * sessions / nullif(lag(sessions) over (order by step_order), 0),
    2
  ) as step_conversion_pct
from steps
order by step_order;

create or replace view public.dashboard_funnel_v2 as
select *
from public.dashboard_assistant_funnel_v2;

create or replace view public.dashboard_demo_paths_v2 as
with session_paths as (
  select
    session_id,
    bool_or(event_name = 'click_assistant') as clicked_assistant,
    bool_or(event_name = 'click_alert') as clicked_alert
  from public.landing_events
  where landing_version = 'v2'
  group by session_id
)
select
  count(*)::bigint as total_demo_sessions,
  count(*) filter (where clicked_assistant)::bigint as assistant_path_sessions,
  count(*) filter (where clicked_alert)::bigint as alert_path_sessions,
  count(*) filter (where clicked_assistant and clicked_alert)::bigint as both_paths_sessions,
  count(*) filter (where clicked_assistant and not clicked_alert)::bigint as only_assistant_sessions,
  count(*) filter (where clicked_alert and not clicked_assistant)::bigint as only_alert_sessions
from session_paths;

create or replace view public.dashboard_alert_clicks_v2 as
select
  coalesce(metadata ->> 'alert_type', 'unknown') as alert_type,
  coalesce(metadata ->> 'click_source', 'unknown') as click_source,
  device_type,
  count(*)::bigint as total_clicks,
  count(distinct session_id)::bigint as unique_sessions
from public.landing_events
where event_name = 'click_alert'
  and landing_version = 'v2'
group by 1, 2, 3
order by total_clicks desc, unique_sessions desc;

create or replace view public.dashboard_lead_sources_v2 as
select
  lead_source,
  count(*)::bigint as total_leads,
  count(distinct session_id)::bigint as unique_sessions,
  round(100.0 * count(*) / nullif(sum(count(*)) over (), 0), 2) as share_pct
from public.landing_leads
where landing_version = 'v2'
group by lead_source
order by total_leads desc;

create or replace view public.dashboard_feature_priority_v2 as
with priorities as (
  select feature_priority
  from public.landing_leads
  where landing_version = 'v2'
    and feature_priority is not null

  union all

  select cs.feature_priority
  from public.chat_sessions cs
  inner join public.landing_sessions ls
    on ls.session_id = cs.session_id
  where ls.landing_version = 'v2'
    and cs.feature_priority is not null
)
select
  feature_priority,
  count(*)::bigint as total
from priorities
group by feature_priority
order by total desc, feature_priority asc;

create or replace view public.dashboard_daily_v2 as
with session_daily as (
  select
    date_trunc('day', started_at)::date as day,
    count(*)::bigint as sessions
  from public.landing_sessions
  where landing_version = 'v2'
  group by 1
),
event_daily as (
  select
    date_trunc('day', created_at)::date as day,
    count(*) filter (where event_name = 'demo_open')::bigint as demo_opens,
    count(*) filter (where event_name = 'click_assistant')::bigint as assistant_clicks,
    count(*) filter (where event_name = 'click_alert')::bigint as alert_clicks,
    count(*) filter (where event_name = 'assistant_user_message_sent')::bigint as assistant_messages,
    count(*) filter (where event_name = 'lead_captured')::bigint as lead_events
  from public.landing_events
  where landing_version = 'v2'
  group by 1
),
lead_daily as (
  select
    date_trunc('day', created_at)::date as day,
    count(*)::bigint as leads,
    count(*) filter (where lead_source = 'form')::bigint as form_leads,
    count(*) filter (where lead_source = 'chat')::bigint as chat_leads
  from public.landing_leads
  where landing_version = 'v2'
  group by 1
)
select
  coalesce(s.day, e.day, l.day) as day,
  coalesce(s.sessions, 0) as sessions,
  coalesce(e.demo_opens, 0) as demo_opens,
  coalesce(e.assistant_clicks, 0) as assistant_clicks,
  coalesce(e.alert_clicks, 0) as alert_clicks,
  coalesce(e.assistant_messages, 0) as assistant_messages,
  coalesce(e.lead_events, 0) as lead_events,
  coalesce(l.leads, 0) as leads,
  coalesce(l.form_leads, 0) as form_leads,
  coalesce(l.chat_leads, 0) as chat_leads
from session_daily s
full outer join event_daily e on e.day = s.day
full outer join lead_daily l on l.day = coalesce(s.day, e.day)
order by day desc;

commit;
