begin;

create table if not exists public.landing_sessions (
  session_id text primary key,
  landing_version text not null default 'v4',
  device_type text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  lead_captured boolean not null default false
);

create table if not exists public.landing_events (
  id bigint generated by default as identity primary key,
  session_id text references public.landing_sessions(session_id) on delete cascade,
  event_name text not null,
  source_section text,
  device_type text,
  landing_version text not null default 'v4',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.landing_leads (
  id bigint generated by default as identity primary key,
  session_id text references public.landing_sessions(session_id) on delete set null,
  email text not null,
  lead_source text,
  landing_version text not null default 'v4',
  feature_priority text,
  experience_rating integer,
  assistant_topic text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  chat_session_id text primary key,
  session_id text not null references public.landing_sessions(session_id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  device_type text,
  entry_point text,
  email_captured boolean not null default false,
  feature_priority text,
  experience_rating integer,
  inferred_topic text
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  chat_session_id text not null references public.chat_sessions(chat_session_id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  message_text text not null,
  message_order integer not null,
  created_at timestamptz not null default now(),
  unique (chat_session_id, message_order)
);

alter table public.landing_sessions add column if not exists landing_version text default 'v4';
alter table public.landing_sessions add column if not exists device_type text;
alter table public.landing_sessions add column if not exists started_at timestamptz default now();
alter table public.landing_sessions add column if not exists ended_at timestamptz;
alter table public.landing_sessions add column if not exists lead_captured boolean default false;

alter table public.landing_events add column if not exists source_section text;
alter table public.landing_events add column if not exists device_type text;
alter table public.landing_events add column if not exists landing_version text default 'v4';
alter table public.landing_events add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.landing_events add column if not exists created_at timestamptz default now();

alter table public.landing_leads add column if not exists lead_source text;
alter table public.landing_leads add column if not exists landing_version text default 'v4';
alter table public.landing_leads add column if not exists feature_priority text;
alter table public.landing_leads add column if not exists experience_rating integer;
alter table public.landing_leads add column if not exists assistant_topic text;
alter table public.landing_leads add column if not exists created_at timestamptz default now();

alter table public.chat_sessions add column if not exists entry_point text;
alter table public.chat_sessions add column if not exists email_captured boolean default false;
alter table public.chat_sessions add column if not exists feature_priority text;
alter table public.chat_sessions add column if not exists experience_rating integer;
alter table public.chat_sessions add column if not exists inferred_topic text;

alter table public.chat_messages add column if not exists message_order integer;
alter table public.chat_messages add column if not exists created_at timestamptz default now();

create index if not exists landing_events_session_idx
  on public.landing_events(session_id, created_at desc);
create index if not exists landing_events_v4_idx
  on public.landing_events(landing_version, event_name, created_at desc);
create index if not exists landing_leads_v4_idx
  on public.landing_leads(landing_version, created_at desc);
create index if not exists chat_messages_session_order_idx
  on public.chat_messages(chat_session_id, message_order);

alter table public.landing_sessions enable row level security;
alter table public.landing_events enable row level security;
alter table public.landing_leads enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

create or replace view public.dashboard_v4_overview as
select
  (select count(*) from public.landing_sessions where landing_version = 'v4') as sessions,
  (select count(*) from public.landing_events where landing_version = 'v4') as events,
  (select count(*) from public.landing_leads where landing_version = 'v4') as leads,
  (
    select count(distinct session_id)
    from public.landing_events
    where landing_version = 'v4'
      and event_name = 'context_assistant_open'
  ) as assistant_open_sessions,
  (
    select count(distinct session_id)
    from public.landing_events
    where landing_version = 'v4'
      and event_name = 'context_assistant_message_sent'
  ) as assistant_message_sessions;

create or replace view public.dashboard_v4_contexts as
select
  coalesce(metadata ->> 'context_key', 'unknown') as context_key,
  event_name,
  count(*)::bigint as total_events,
  count(distinct session_id)::bigint as unique_sessions
from public.landing_events
where landing_version = 'v4'
  and event_name in (
    'context_assistant_open',
    'context_assistant_suggestion_click',
    'context_assistant_message_sent'
  )
group by 1, 2
order by total_events desc;

revoke all on table public.landing_sessions from anon, authenticated;
revoke all on table public.landing_events from anon, authenticated;
revoke all on table public.landing_leads from anon, authenticated;
revoke all on table public.chat_sessions from anon, authenticated;
revoke all on table public.chat_messages from anon, authenticated;
revoke all on table public.dashboard_v4_overview from anon, authenticated;
revoke all on table public.dashboard_v4_contexts from anon, authenticated;

commit;
